using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Humanizer;
using MimeKit;
using EntityLayer.DTOs;
using MailKit.Net.Smtp;

namespace CVSharer.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Contact() 
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Contact(MailDTO dto)
        {
            MimeMessage message = new MimeMessage();

            MailboxAddress mailboxAddressFrom = new MailboxAddress(dto.SenderMail, "huseyinkaradana35@gmail.com");

            message.From.Add(mailboxAddressFrom);

            MailboxAddress mailboxAddressTo = new MailboxAddress("CVSharer", "sharercv@gmail.com");
            message.To.Add(mailboxAddressTo);

            var bodyBuilder = new BodyBuilder();
            bodyBuilder.HtmlBody = "<!DOCTYPE html>\r\n\r\n<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n<head>\r\n<title></title>\r\n<meta content=\"text/html; " +
                "charset=utf-8\" http-equiv=\"Content-Type\"/>\r\n<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/>" +
                "</o:OfficeDocumentSettings></xml><![endif]-->\r\n<style>\r\n\t\t* {\r\n\t\t\tbox-sizing: border-box;\r\n\t\t}\r\n\r\n\t\tbody {\r\n\t\t\tmargin: 0;\r\n\t\t\tpadding: 0;\r\n\t\t}\r\n\r\n\t\ta[x-apple-data-detectors] {\r\n\t\t\tcolor: inherit !important;\r\n\t\t\ttext-decoration: inherit !important;\r\n\t\t}\r\n\r\n\t\t#MessageViewBody a {\r\n\t\t\t" +
                "color: inherit;\r\n\t\t\ttext-decoration: none;\r\n\t\t}\r\n\r\n\t\tp {\r\n\t\t\tline-height: inherit\r\n\t\t}\r\n\r\n\t\t.desktop_hide,\r\n\t\t.desktop_hide table {\r\n\t\t\tmso-hide: all;\r\n\t\t\tdisplay: none;\r\n\t\t\t" +
                "max-height: 0px;\r\n\t\t\toverflow: hidden;\r\n\t\t}\r\n\r\n\t\t.image_block img+div {\r\n\t\t\tdisplay: none;\r\n\t\t}\r\n\r\n\t\t.menu_block.desktop_hide .menu-links span {\r\n\t\t\tmso-hide: all;\r\n\t\t}\r\n\r\n\t\t#memu-r7c0m2:checked~.menu-links {\r\n\t\t\tbackground-color: #000 !important;\r\n\t\t}\r\n\r\n\t\t#memu-r7c0m2:checked~.menu-links a,\r\n\t\t#memu-r7c0m2:checked~.menu-links span {\r\n\t\t\tcolor: #fff !important;\r\n\t\t}\r\n\r\n\t\t@media (max-width:700px) {\r\n\t\t\t.desktop_hide table.icons-inner {\r\n\t\t\t\tdisplay: inline-block !important;\r\n\t\t\t}\r\n\r\n\t\t\t" +
                ".icons-inner {\r\n\t\t\t\ttext-align: center;\r\n\t\t\t}\r\n\r\n\t\t\t.icons-inner td {\r\n\t\t\t\tmargin: 0 auto;\r\n\t\t\t}\r\n\r\n\t\t\t.image_block img.fullWidth {\r\n\t\t\t\tmax-width: 100% !important;\r\n\t\t\t}\r\n\r\n\t\t\t.menu-checkbox[type=checkbox]~.menu-links {\r\n\t\t\t\tpadding: 5px 0;\r\n\t\t\t\tdisplay: none !important;\r\n\t\t\t}\r\n\r\n\t\t\t.menu-checkbox[type=checkbox]:checked~.menu-links,\r\n\t\t\t.menu-checkbox[type=checkbox]~.menu-trigger {\r\n\t\t\t\tfont-size: inherit !important;\r\n\t\t\t\tmax-width: none !important;\r\n\t\t\t\tmax-height: none !important;\r\n\t\t\t\tdisplay: block !important;\r\n\t\t\t}\r\n\r\n\t\t\t.menu-checkbox[type=checkbox]~.menu-links>a,\r\n\t\t\t.menu-checkbox[type=checkbox]~.menu-links>span.label {\r\n\t\t\t\ttext-align: center;\r\n\t\t\t\t" +
                "display: block !important;\r\n\t\t\t}\r\n\r\n\t\t\t.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-close {\r\n\t\t\t\tdisplay: block !important;\r\n\t\t\t}\r\n\r\n\t\t\t.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-open {\r\n\t\t\t\tdisplay: none !important;\r\n\t\t\t}\r\n\r\n\t\t\t.social_block.desktop_hide .social-table {\r\n\t\t\t\tdisplay: inline-block !important;\r\n\t\t\t}\r\n\r\n\t\t\t.row-content {\r\n\t\t\t\twidth: 100% !important;\r\n\t\t\t}\r\n\r\n\t\t\t.stack .column {\r\n\t\t\t\twidth: 100%;\r\n\t\t\t\tdisplay: block;\r\n\t\t\t}\r\n\r\n\t\t\t.mobile_hide {\r\n\t\t\t\tmax-width: 0;\r\n\t\t\t\tmin-height: 0;\r\n\t\t\t\tmax-height: 0;\r\n\t\t\t\tfont-size: 0;\r\n\t\t\t\tdisplay: none;\r\n\t\t\t\toverflow: hidden;\r\n\t\t\t}\r\n\r\n\t\t\t.desktop_hide,\r\n\t\t\t" +
                ".desktop_hide table {\r\n\t\t\t\tmax-height: none !important;\r\n\t\t\t\tdisplay: table !important;\r\n\t\t\t}\r\n\t\t}\r\n\t</style>\r\n</head>\r\n<body style=\"text-size-adjust: none; background-color: #fff0e3; margin: 0; padding: 0;\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff0e3;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt;" +
                " mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n<div class=\"spacer_block block-1\" style=\"height:30px;line-height:30px;font-size:1px;\"> </div>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n" +
                "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n<td class=\"column column-2\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px;" +
                " padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n<div align=\"center\" class=\"alignment\" style=\"line-height:10px;\"><img alt=\"Company Logo\" src=\"https://lh3.googleusercontent.com/-QR5_BREHrH4/WYbwI3ULn0I/AAAAAAAAAA8/rabsHLGKv9MFOPw6861nwx_ECONiPiYTACLIBGAYYCw/w1080-h608-p-k-no-v0/\"  style=\"height: auto; display: block; border: 0;width: 300px; \" title=\"Company Logo\" width=\"147.33333333333331\"/></div>\r\n</td>\r\n</tr>\r\n" +
                "</table>\r\n</td>\r\n<td class=\"column column-3\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt;" +
                " mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n<div class=\"spacer_block block-1\" style=\"height:10px;line-height:10px;font-size:1px;\"> </div>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n" +
                "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"width:100%;\">\r\n<div align=\"center\" class=\"alignment\" style=\"line-height:10px\">" +
                "<img alt=\"Top round corners\" src=\"https://i.hizliresim.com/hcc19oe.png\" style=\"height: auto; display: block; border: 0; max-width: 680px; width: 100%;\" title=\"Top round corners\" width=\"680\"/></div>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; background-color: #fff; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n" +
                "<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n\r\n<div class=\"spacer_block block-2\" style=\"height:35px;line-height:35px;font-size:1px;\"> </div>\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n<h1 style=\"margin: 0; color: #101010; direction: ltr; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 27px; font-weight: normal; letter-spacing: normal; " +
                "line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0;\"><strong>Subject</strong></h1>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-6\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; background-color: #fff; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left;" +
                " font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"16.666666666666668%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n<td class=\"column column-2\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"padding-bottom:10px;" +
            "padding-left:20px;padding-right:10px;padding-top:10px;\">\r\n<div style=\"font-family: sans-serif\">\r\n<div class=\"\" style=\"font-size: 12px; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 21.6px; color: #848484; line-height: 1.8;\">\r\n<p style=\"margin: 0; font-size: 14px; mso-line-height-alt: 25.2px;\"><span><h3 style=\"display: inline-block;font-size: 15px;\">Customer:</h3>&emsp;<h3 style=\"color: black;display: inline-block; font-size: 15px;\">" + dto.Name + "</h3> <br>\r\n\t<h3 style=\"display: inline-block;font-size: 15px;\">Email:</h3>&emsp;<h3 style=\"color: black;display: inline-block; font-size: 15px;\">" + dto.SenderMail + "</h3>\r\n\t<h2  style=\"text-align: center;font-size: 25px;\" >" + dto.Subject + "</h2>\r\n\t<hr> <br>\r\n\t<p style=\"font-size: 18px;\">" + dto.Body + "</p>\r\n</span></p>\r\n</div>\r\n</div>\r\n</td>\r\n" +
            "</tr>\r\n</table>\r\n<div class=\"spacer_block block-2\" style=\"height:10px;line-height:10px;font-size:1px;\"> </div>\r\n<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" class=\"button_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n\r\n</tr>\r\n</table>\r\n<div class=\"spacer_block block-4\" style=\"height:20px;line-height:20px;font-size:1px;\"> </div>\r\n</td>\r\n<td class=\"column column-3\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"16.666666666666668%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n" +
            "</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-7\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n" +
            "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"width:100%;\">\r\n<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><img alt=\"Bottom round corners\" src=\"https://i.hizliresim.com/emtaegg.png\" style=\"height: auto; display: block; border: 0; max-width: 680px; width: 100%;\" title=\"Bottom round corners\" width=\"680\"/></div>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-8\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n" +
                "<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n<div class=\"spacer_block block-1\" style=\"height:20px;line-height:20px;font-size:1px;\"> </div>\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"social_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n" +
                "<tr>\r\n<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px;text-align:center;\">\r\n<div align=\"center\" class=\"alignment\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"social-table\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\" width=\"144px\">\r\n<tr>\r\n<td style=\"padding:0 2px 0 2px;\"><a href=\"https://www.facebook.com\" target=\"_blank\"><img alt=\"Facebook\" height=\"32\" src=\"https://i.hizliresim.com/jxktlxd.png\" style=\"height: auto; display: block; border: 0;\" title=\"facebook\" width=\"32\"/></a></td>\r\n<td style=\"padding:0 2px 0 2px;\"><a href=\"https://www.twitter.com\" target=\"_blank\"><img alt=\"Twitter\" height=\"32\" src=\"https://i.hizliresim.com/sn76wik.png\" style=\"height: auto;" +
                " display: block; border: 0;\" title=\"twitter\" width=\"32\"/></a></td>\r\n<td style=\"padding:0 2px 0 2px;\"><a href=\"https://www.linkedin.com\" target=\"_blank\"><img alt=\"Linkedin\" height=\"32\" src=\"https://i.hizliresim.com/gsxiijz.png\" style=\"height: auto; display: block; border: 0;\" title=\"linkedin\" width=\"32\"/></a></td>\r\n<td style=\"padding:0 2px 0 2px;\"><a href=\"https://www.instagram.com\" target=\"_blank\"><img alt=\"Instagram\" height=\"32\" src=\"https://i.hizliresim.com/35qkdlk.png\" style=\"height: auto; display: block; border: 0;\" title=\"instagram\" width=\"32\"/></a></td>\r\n</tr>\r\n</table>\r\n</div>\r\n</td>\r\n</tr>\r\n</table>\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"menu_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n" +
                "<tr>\r\n<td class=\"pad\" style=\"color:#101010;font-family:inherit;font-size:14px;text-align:center;\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"alignment\" style=\"text-align:center;font-size:0px;\"><!--[if !mso]><!--><input class=\"menu-checkbox\" id=\"memu-r7c0m2\" style=\"display:none !important;max-height:0;visibility:hidden;\" type=\"checkbox\"/><!--<![endif]-->\r\n<div class=\"menu-trigger\" style=\"display:none;max-height:0px;max-width:0px;font-size:0px;overflow:hidden;\"><label class=\"menu-label\" for=\"memu-r7c0m2\" style=\"height: 36px; width: 36px; display: inline-block; cursor: pointer; mso-hide: all; user-select: none; align: center; text-align: center; color: #ffffff; text-decoration: none;" +
                " background-color: #000000; border-radius: 0%;\"><span class=\"menu-open\" style=\"mso-hide:all;font-size:26px;line-height:31.5px;\">☰</span><span class=\"menu-close\" style=\"display:none;mso-hide:all;font-size:26px;line-height:36px;\">✕</span></label></div>\r\n<div class=\"menu-links\"><!--[if mso]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" style=\"\"><tr style=\"text-align:center;\"><![endif]--><!--[if mso]><td style=\"padding-top:5px;padding-right:15px;padding-bottom:5px;padding-left:15px\"><![endif]--><a href=\"www.example.com\" style=\"mso-hide:false;padding-top:5px;padding-bottom:5px;padding-left:15px;padding-right:15px;display:inline-block;color:#101010;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:14px;text-decoration:none;letter-spacing:normal;\" target=\"_self\">" +
                "Unsubscribe</a><!--[if mso]></td><![endif]--><!--[if mso]><td style=\"padding-top:5px;padding-right:15px;padding-bottom:5px;padding-left:15px\"><![endif]--><a href=\"www.example.com\" style=\"mso-hide:false;padding-top:5px;padding-bottom:5px;padding-left:15px;padding-right:15px;display:inline-block;color:#101010;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:14px;text-decoration:none;letter-spacing:normal;\" target=\"_self\">Help</a><!--[if mso]></td><![endif]--><!--[if mso]><td style=\"padding-top:5px;padding-right:15px;padding-bottom:5px;padding-left:15px\"><![endif]--><a href=\"www.example.com\" style=\"mso-hide:false;padding-top:5px;padding-bottom:5px;padding-left:15px;padding-right:15px;display:inline-block;color:#101010;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:14px;text-decoration:none;" +
                "letter-spacing:normal;\" target=\"_self\">Login</a><!--[if mso]></td><![endif]--><!--[if mso]><td style=\"padding-top:5px;padding-right:15px;padding-bottom:5px;padding-left:15px\"><![endif]--><a href=\"www.example.com\" style=\"mso-hide:false;padding-top:5px;padding-bottom:5px;padding-left:15px;padding-right:15px;display:inline-block;color:#101010;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:14px;text-decoration:none;letter-spacing:normal;\" target=\"_self\">Privacy</a><!--[if mso]></td><![endif]--><!--[if mso]></tr></table><![endif]--></div>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-9\" role=\"presentation\" style=\"mso-table-lspace: 0pt;" +
                " mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"16.666666666666668%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n<td class=\"column column-2\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400;" +
                " padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\r\n<div class=\"spacer_block block-1\" style=\"height:35px;line-height:35px;font-size:1px;\"> </div>\r\n</td>\r\n<td class=\"column column-3\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"16.666666666666668%\">\r\n<div class=\"spacer_block block-1\" style=\"height:0px;line-height:0px;font-size:1px;\"> </div>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-10\" role=\"presentation\" style=\"mso-table-lspace: 0pt;" +
                " mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000; width: 680px; margin: 0 auto;\" width=\"680\">\r\n<tbody>\r\n<tr>\r\n<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: left; font-weight: 400; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"icons_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"pad\" style=\"vertical-align: middle; " +
                "color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\r\n<table cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n<tr>\r\n<td class=\"alignment\" style=\"vertical-align: middle; text-align: center;\"><!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n<!--[if !vml]><!-->\r\n<table cellpadding=\"0\" cellspacing=\"0\" class=\"icons-inner\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\"><!--<![endif]-->\r\n\r\n</table>\r\n" +
                "</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table><!-- End -->\r\n</body>\r\n</html>";

            message.Body = bodyBuilder.ToMessageBody();
            message.Subject = dto.Subject;


            SmtpClient client = new SmtpClient();
            client.Connect("smtp.gmail.com", 587, false);
            client.Authenticate("huseyinkaradana35@gmail.com", "bpdifyzhksdygxjy");
            client.Send(message);
            client.Disconnect(true);
            return RedirectToAction("Contact", "Home");
        }


        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Terms()
        {
            return View();
        }
    }
}
